Repository hmcts/em-hrs-api, pull requests merged in 2021-03, with the labels that each got.

#51 Updated the image name
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-51

#52 concatanated partial build.gradle files to match spring boot template…
  build-code-checks.gradle
  build-code-coverage.gradle
  build-dependencies.gradle
  build-dependency-management.gradle
  build-source-sets.gradle
  build-tasks.gradle
  build.gradle
  config/owasp/suppressions.xml
  liquibase.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-52

#56 Added in storage account secrets
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-hrs-api-pr-56

#57 Added storage account details to preview
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-hrs-api-pr-57

#65 Em 3582 verify logging
  build.gradle
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-hrs-api-pr-65

#71 remove maven local and promote order of maven central over jcenter as…
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-71

#73 downgrade ben manes library
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-73

#79 EM-3413 Create Service and Repository Layers
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/FolderRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingShareesRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareService.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImplTests.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesServiceImplTests.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-79

#78 Added in changes for S2S auth
  build.gradle
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  config/checkstyle/checkstyle.xml
  docker-compose-dependencies.yml
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/GetRootUrlTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/BaseTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/TestSecurityConfiguration.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-78

#82 Fixed CVE-2021-21295
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-82

#81 EM-3401 Implement copy from CVP blobstore to HRS blobstore
  Makefile
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/GetRootUrlTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureOperations.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/SimpleSnooper.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/FolderRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/ApplicationConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/SwaggerConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/azure/AzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/azure/MetaDataAzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/DefaultSnooper.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/SetUtils.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/Snooper.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/Tuple2.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/AbstractBaseTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/AbstractDataSourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/BaseTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingServiceImplTests.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-81

#87 Fixed CVE-2020-15824, CVE-2020-29582
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-87

#88 Initial Version of the Security Tests for the pipeline....
  Jenkinsfile_nightly
  audit.json
  security.sh
Labels: ns:em, prd:em, rel:em-hrs-api-pr-88

#89 Em 3395 metadata persist to db
  src/integrationTest/resources/application-test.yaml
  src/integrationTest/resources/data/create-folder.sql
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegment.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImplTests.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-89

#90 Em 3647
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-90
