Repository hmcts/em-hrs-api, pull requests merged in 2021-08, with the labels that each got.

#349 Added hikari config with same defaults as DM store
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-349

#357 EM-4007: fix CVE-2021-22119
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-357

#365 upgrade gradle version
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:em, prd:em, rel:em-hrs-api-pr-365

#376 refactored role names and users initiating shares and updated to gov …
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-376

#381 EM-4024: fix terraform version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-hrs-api-pr-381
