Repository hmcts/em-hrs-api, pull requests merged in 2022-03, with the labels that each got.

#553 bump spring boot 2.6
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreatorTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-553

#580 use HRS email user and password
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-580

#583 fix nightly build
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-583

#586 Resolved functional tests issue
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-586

#585 update postgres version to 11 for local setup
  docker-compose-dependencies.yml
  docker/postgres9-shared-dbs/Dockerfile
Labels: ns:em, prd:em, rel:em-hrs-api-pr-585

#589 remove jcenter
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-589

#591 bump java chart
  charts/em-hrs-api/Chart.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-591

#593 EM-4294 use HMCTS jitpack dependencies
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-593

#600 Updated Sonarqube config
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-600

#602 remove java plugin
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-602

#603 revert gradle-build changes
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-603

#598 Em 4297 use jparepository to flush
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-598

#612 clean up dependency management
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-612

#614 clean up dependency management-remove commons-io
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-614

#615 EM-4278 use now for createon field
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-615

#626 Fix CVE-2020-36518
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-626

#631 upgrade azurerm provider
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-hrs-api-pr-631

#625 Update dependabot.yml
  .github/dependabot.yml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-625

#636 Updated azurerm & terraform version
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:em, prd:em, rel:em-hrs-api-pr-636

#637 Fix CVE-2022-21724
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-637
