Repository hmcts/em-hrs-api, pull requests merged in 2022-05, with the labels that each got.

#650 EM-4387: update the sonar exclusions
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-650

#666 Updated config for Renovate Bot
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-666

#670 Fixed CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-670

#672 Removed dependabot config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-672
