Repository hmcts/em-hrs-api, pull requests merged in 2022-08, with the labels that each got.

#689 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-689

#694 Flyway migration on AAT & Prod
  README.md
  build.gradle
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  gradle.properties
  liquibase.gradle
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/data/migration/PendingMigrationScriptException.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1__baseline_migration.sql
  src/main/resources/liquibase.properties
  src/test/resources/application-test.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-694

#695 Add backstage configuration file
  catalog-info.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-695
