Repository hmcts/em-hrs-api, pull requests merged in 2023-04, with the labels that each got.

#1109 Updated CVE list
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1109

#1121 Em-5186remove security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1121

#1123 EM-5186 remove root from swagger
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1123

#1124 EM-5186 suppress security vulnerabilities
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1124

#1127 EM-5186 Update audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1127

#1132 Created Welcome Controller and test
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/WelcomeController.java
  src/smokeTest/java/uk/gov/hmcts/reform/em/hrs/smoke/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/WelcomeControllerTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1132

#1135 EM-5084 create vh container
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1135

#1143 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1143

#1136 fix preview storage for functional tests
  Jenkinsfile_CNP
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/functionalTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1136

#1047 EM-5080 enable fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1047

#1148 EM-5085 add vh connection configs
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/functionalTest/resources/application.yml
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1148

#1153 EM-5087 add new column for hearing_source
  src/main/resources/db/migration/V3__add_hearing_source_column_folder.sql
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1153
