Repository hmcts/em-hrs-api, pull requests merged in 2023-01, with the labels that each got.

#945 EM-4912-suppress-vulnerability
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-945

#958 Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-958

#961 EM-4943 suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-961

#970 Fix CVE & Revert "Bump org.flywaydb.flyway from 9.8.3 to 9.11.0"
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-970

#1001 EM-5015 bump-hmcts.java
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1001
