Repository hmcts/em-hrs-api, pull requests merged in 2023-09, with the labels that each got.

#1375 Resolve CVE-2023-41080
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1375

#1377 avoid from CVE-2023-41080
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1377

#1371 EM-5094 add func test
  Jenkinsfile_CNP
  build.gradle
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/BlobUtil.java
  src/functionalTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/FolderController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobIndexMarker.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1371

#1395 fix preview blobstorage aSo
  Jenkinsfile_CNP
  charts/em-hrs-api/values.preview.template.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1395

#1397 Update Renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1397

#1416 Em 5551 update renovate config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1416

#1412 EM-5093 add vh sharee logic
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareScenariosVh.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClient.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1412

#1418 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1418

#1425 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1425

#1438 EM-5569 extend vulnerability suppress
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1438
