Repository hmcts/em-hrs-api, pull requests merged in 2023-08, with the labels that each got.

#1336 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1336

#1331 Upgrade: java-logging 6.0.1
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1331

#1344 EM-5322 Add vh hrs blob client
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/FolderController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImplTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1344

#1347 EM-5322 use enum for hearingSource
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/dto/HearingRecordingDto.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/job/CcdUploadJobTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreatorTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1347

#1349 em-5482: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1349

#1352 create cvp simulator container
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1352

#1355 Em-5091 check case existence and mark blob index
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobIndexMarker.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/storage/BlobIndexMarkerTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1355

#1359 Update Checkstyle
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1359

#1361 EM-5498 add interpreter column to hearing_recording_segment
  src/main/resources/db/migration/V5__add_interpreter_column_hearing_recording_segment.sql
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1361

#1367 em-5502: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1367

#1365 EM-5498 add interpreter to Dto
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegment.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/dto/HearingRecordingDto.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1365
