Repository hmcts/em-hrs-api, pull requests merged in 2023-03, with the labels that each got.

#1055 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1055

#1056 Updated CVE list
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1056

#1084 Resolve CVE-2022-1471
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1084

#1095 Removed dependency and upgraded app insights
  Dockerfile
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1095

#1103 Em-5155 remove list permission
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1103
