Repository hmcts/em-hrs-api, pull requests merged in 2023-11, with the labels that each got.

#1500 em-5640 - added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1500

#1509 Updated force_user_permissions_trigger
  infrastructure/main.tf
Labels: ns:em, prd:em, Do Not Merge, destroy, rel:em-hrs-api-pr-1509

#1517 EM-5649 bump java and app insight jar
  Dockerfile
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1517

#1520 Removed v11 DB details
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
Labels: ns:em, prd:em, destroy, rel:em-hrs-api-pr-1520

#1523 Updated v15 DB connection details
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1523

#1524 Revert "Updated v15 DB connection details"
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1524

#1532 Removed v11 DB details
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-hrs-api-pr-1532

#1540 EM-5679 suppress CVE-2023-36052
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1540
