Repository hmcts/em-hrs-api, pull requests merged in 2023-05, with the labels that each got.

#1162 EM-5230 avoid CVE-2023-20862
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1162

#1174 Refer to new AppInsights details
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1174

#1190 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1190

#1192 EM-5282 fix master build
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1192
