Repository hmcts/em-hrs-api, pull requests merged in 2023-07, with the labels that each got.

#1261 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1261

#1271 EM-5322 rename env var
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1271

#1272 EM-5322 rename properties
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.preview.template.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/functionalTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1272

#1235 EM-5119 spring 3 upgrade
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadNonSharedScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AuthTokenGeneratorConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorControllerTest.java
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/em/hrs/Application.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/appinsights/AppInsightConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/AuditEntry.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/Folder.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingAuditEntry.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegment.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegmentAuditEntry.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSharee.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingShareeAuditEntry.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/JobInProgress.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/exception/InvalidRangeRequestException.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/job/CcdUploadJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/FolderRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingAuditEntryRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentAuditEntryRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesAuditEntryRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSender.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/HttpHeaderProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/debug/HttpHeadersLogging.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSenderTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/util/HttpHeaderProcessorTest.java
  src/test/resources/application-test.yaml
Labels: ns:em, prd:em, add-or-update, rel:em-hrs-api-pr-1235

#1277 remove debug/info log level
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1277

#1287 try to fix pact error
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1287

#1289 Fix pact error -revert pact&serenity bump
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1289

#1288 REMOVE 'com.github.hmcts', name: 'auth-checker-lib'
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1288

#1290 em-5398: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1290

#1291 Upgrade Gradle Version 8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1291

#1274 EM-5322 use vh storage connection
  charts/em-hrs-api/Chart.yaml
  charts/em-hrs-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolver.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolverTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1274

#1293 add Vh counting
  src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1293
