Repository hmcts/em-hrs-api, pull requests merged in 2024-01, with the labels that each got.

#1605 EM-5729 try to fix dbmigration
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1605

#1606 revert PR-1605
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1606

#1607 Em 5744 resolve CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1607

#1609 extend owasp suppressions
  config/owasp/suppressions.xml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1609

#1629 add graceful shutdown
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1629

#1632 Upgrading to java 21
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1632

#1633 EM-5801 - bump pitest plugin
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-1633
