Repository hmcts/em-hrs-api, pull requests merged in 2024-09, with the labels that each got.

#2025 Em 6190 local setup
  README.md
  build.gradle
  src/cftlib/java/uk/gov/hmcts/reform/em/hrs/cftlib/CftLibConfig.java
  src/cftlib/resources/docker-compose-local.yml
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
  src/main/resources/application.yaml
  src/main/resources/cftlib-am-role-assignments.json
Labels: ns:em, prd:em, aat/add-or-update, prod/add-or-update, rel:em-hrs-api-pr-2025

#2042 EM-6254 avoid using connection key
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2042

#2045 EM-6254 fix nightly build
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2045
