Repository hmcts/em-hrs-api, pull requests merged in 2025-05, with the labels that each got.

#2477 Em 6626 add indexes
  src/main/resources/db/migration/V12__add_indexes.sql
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2477

#2474 EM-6625: remove ttlSet column
  src/functionalTest/resources/data/populate_db.sql
  src/integrationTest/resources/data/create-folder.sql
  src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/job/UpdateTtlJob.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/main/resources/db/migration/V13__remove_ttl_set_column_hearing_recordings.sql
  src/test/java/uk/gov/hmcts/reform/em/hrs/job/UpdateTtlJobTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2474

#2497 Removed redundant rules
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2497
