Repository hmcts/em-hrs-api, pull requests merged in 2025-01, with the labels that each got.

#2238 Em 6345 junit5 upgrade 1
  src/contractTest/java/uk/gov/hmcts/reform/em/hrs/consumer/IdamApiPactConsumerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadNonSharedScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/FolderScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/SecurityScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareScenariosVh.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/FolderControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/DateListConverterTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSenderTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportTaskTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/AuditEntryServiceTests.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/SegmentDownloadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/ShareServiceImplTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2238

#2244 Em-6345 remove junit4 and bump pitest
  build.gradle
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2244

#2263 upgrade em-test-helper to 2.1.1
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
Labels: ns:em, prd:em

#2264 EM-6395 fix TTL base time
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/TtlService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImplTest.java
Labels: ns:em, prd:em

#2270 Revert "Update Terraform azurerm to ~> 4.16.0 (#2269)"
  infrastructure/state.tf
Labels: ns:em, prd:em, aat/add-or-update, prod/add-or-update

#2271 populate the service and jurisdiction codes
  src/main/resources/ttl_jurisdiction_map.json
  src/main/resources/ttl_service_map.json
Labels: ns:em, prd:em, aat/add-or-update, prod/add-or-update

#2284 Revert "Update Terraform azurerm to ~> 4.16.0 (#2278)"
  infrastructure/state.tf
Labels: ns:em, prd:em, aat/add-or-update, prod/add-or-update

#2285 EM-6404 refactor - remove methods or make private
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityService.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java
  src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/SecurityServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClientTest.java
  src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/SecurityServiceImplTest.java
Labels: ns:em, prd:em, rel:em-hrs-api-pr-2285
